/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
    turorialSidebar: [
        'intro',
        '29 Pedals',
        'Backelite Boutique Pedals',
        'Buzztone Audio Effects',
        'Cascade Pedals',
        'Cat Box Customs',
        'Collision Devices',
        'Dead Air',
        'Demonic Machines',
        'Dogman Devices',
        'dunn effects',
        'ExtraTerrestrial Products',
        'Gojira FX',
        'Heathencraft fx',
        'LEEMS Industries LLC',
        'Mattoverse Electronics',
        'Pedal Brainz',
        'Radio Mule',
        'Soundslicefx',
        'SPS Pedals',
        'Vertigo Noise',

    ]
   
};

module.exports = sidebars;
